version: '3'
services:
  dev:
    image: thesis
    environment:
      DISPLAY: ${DISPLAY}
      FILE_PATH: /root/launch_files/
      ROS_MASTER_URI: http://localhost:11311
    depends_on:
      - roscore
    volumes:
      - /etc/hosts:/etc/hosts
      - "${HOME}/.Xauthority:/root/.Xauthority:rw"
      - /Documents/git/Docker/directory_exam-ple:/root/launch_files
      - /home/jarne/Documents/Thesis/Limo_thesis:/home/Thesis
    network_mode: host
    command: bash
    tty: true
    stdin_open: true
    restart: always
    container_name: dev

  roscore:
    container_name: roscore
    image: thesis
    network_mode: "host"
    restart: always
    tty: true
    privileged: true
    command: roscore

  gazebo:
    image: woensugchoi/glider_hybrid_whoi:latest
    environment:
      DISPLAY: ${DISPLAY}
      FILE_PATH: /root/launch_files/
      ROS_MASTER_URI: http://localhost:11311
    volumes:
      - /Documents/git/Docker/directory_exam-ple:/root/launch_files
      - /home/jarne/Documents/Thesis/Limo_thesis:/home/Thesis
    command:
      - roslaunch
      - --wait
      - /home/Thesis/src/ugv_sim/limo/limo_gazebo_sim/launch/limo_ackerman.launch
      - latitude:=${LATITUDE:-41.5522}
      - longitude:=${LONGITUDE:--70.6803}
    privileged: true




