version: '3'
services:

  roscore:
    container_name: roscore
    image: thesis
    network_mode: "host"
    restart: always
    command: zsh -c 'source ~/.zshrc && roscore'
    tty: true
    privileged: true
    volumes:
      - "./:/home/:rw"

  terminal:
    depends_on:
      - roscore
    container_name: terminal
    image: thesis
    network_mode: host
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    tty: true
    stdin_open: true

  rviz:
    depends_on:
      - roscore
    container_name: rviz
    image: thesis
    runtime: nvidia
    network_mode: host
    command: zsh -c 'source ~/.zshrc && rviz'
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    tty: true
    restart: always
    stdin_open: true

  gazebo:
    depends_on:
      - rviz
      - roscore
    container_name: gazebo
    image: thesis
    runtime: nvidia
    network_mode: host
    command: zsh -c 'source ~/.zshrc && gazebo'
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    tty: true
    stdin_open: true



  # dev2:
  #   image: thesis
  #   environment:
  #     DISPLAY: ${DISPLAY}
  #     FILE_PATH: /root/launch_files/
  #     ROS_MASTER_URI: http://localhost:11311
  #   depends_on:
  #     - roscore2
  #   volumes:
  #     - /etc/hosts:/etc/hosts
  #     - "${HOME}/.Xauthority:/root/.Xauthority:rw"
  #     - /Documents/git/Docker/directory_exam-ple:/root/launch_files
  #     - /home/jarne/Documents/Thesis/Limo_thesis:/home/Thesis
  #   network_mode: host
  #   command: bash
  #   tty: true
  #   stdin_open: true
  #   restart: always
  #   container_name: dev2
